### ISSUE TITLE
Encountered edid built error for a V3-hat

### ISSUE THREAD

**Issue by emorytaylor** [Kreeblah/blikvm_pikvm_build#1]
Ran sucessfully until 62/70. Looks like it is a small configuation error but it isn't immediately obvious to me since EDID might as well be magic so hopefully you'll know. 

Thanks for this, I'm looking forward to getting a more standard pikvm setup.

```
=> ERROR [62/70] RUN kvmd-edidconf --restore-default=v3                                                                                                                          1.7s
------
 > [62/70] RUN kvmd-edidconf --restore-default=v3:
1.252 usage: kvmd-edidconf [-h] [-f <file>] [--export-hex <file>]
1.252                      [--export-bin <file>] [--import <file>]
1.252                      [--import-preset { v0 | v1 | v2 | v3 | v4mini | v4plus | v0.1080p-by-default | v1.1080p-by-default | v2.1080p-by-default | v3.1080p-by-default | v4mini.no-1920x1200 | v4plus.no-1920x1200 }]
1.252                      [--set-audio <yes|no>] [--set-mfc-id <ABC>]
1.252                      [--set-product-id <uint>] [--set-serial <uint>]
1.252                      [--set-monitor-name <str>] [--set-monitor-serial <str>]
1.252                      [--clear] [--apply] [--device <device>] [--presets <dir>]
1.253 kvmd-edidconf: error: unrecognized arguments: --restore-default=v3
------
Dockerfile:261
--------------------
 259 |     COPY stages/blikvm/override.yaml /etc/kvmd/override.yaml
 260 |     
 261 | >>> RUN kvmd-edidconf --restore-default=$EDIDTYPE
 262 |     RUN kvmd-edidconf --set-audio=1
 263 |     
--------------------
ERROR: failed to solve: process "/bin/sh -c kvmd-edidconf --restore-default=$EDIDTYPE" did not complete successfully: exit code: 2
make[1]: *** [Makefile:184: os] Error 1
make[1]: Leaving directory '/home/emory/blikvm_pikvm_build/.pi-builder/v3-hat-rpi4'
make: *** [Makefile:98: os] Error 2

```

**Comment by Kreeblah** [comment]
Hmmm.  Looks like https://github.com/pikvm/kvmd/commit/5088e7d645d4d3685e5e34991e27cca6a693e712 changed that parameter from `--restore-default` to `--import-preset`.  That should be a simple enough fix.  I don't have time to get that fixed just now, but I'll get that updated in the next day or so.

That said, I don't have a V3, so I have no idea whether the end result is going to work for you.  I'll be curious to hear how it goes once you get an image built, though.

**Comment by emorytaylor** [comment]
great thanks I'll test it when you update it and let you know

**Comment by Kreeblah** [comment]
I pushed an update, so it's building for me now for my V2 PCIe.  You should be good go give it another go.

**Comment by emorytaylor** [comment]
I got *almost* all the way through it. I'm going to bed but I got an error during image creation part. Looks like the regex isn't finding what it wants. Let me know if you need any more information. Thanks!
```
===== Extraction complete =====
===== Creating image /home/emory/blikvm_pikvm_build/images/blikvm-pikvm-v3-hat-rpi4-20240525.img =====
rm -f /home/emory/blikvm_pikvm_build/images/blikvm-pikvm-v3-hat-rpi4-20240525.img /home/emory/blikvm_pikvm_build/images/blikvm-pikvm-v3-hat-rpi4-20240525.img.sha1 /home/emory/blikvm_pikvm_build/images/blikvm-pikvm-v3-hat-rpi4-20240525.img.xz /home/emory/blikvm_pikvm_build/images/blikvm-pikvm-v3-hat-rpi4-20240525.img.xz.sha1
touch ./.cache/blikvm-pikvm-os.v3-hat.arch-rpi4-arm.img
cat /home/emory/blikvm_pikvm_build/upstream_os/disk/v3.conf | docker run --rm --interactive \
		--volume=/dev:/root/dev \
		--privileged \
		--volume=/home/emory/blikvm_pikvm_build/.pi-builder/v3-hat-rpi4/./.cache:/root/./.cache --workdir=/root/./.cache/.. \
	pi-builder.blikvm-pikvm-os.v3-hat.toolbox \
		/tools/install \
			--compress \
			--devfs-prefix=/root \
			--root=./.cache/blikvm-pikvm-os.v3-hat.arch-rpi4-arm.rootfs \
			--image=./.cache/blikvm-pikvm-os.v3-hat.arch-rpi4-arm.img
CMD [ /tools/install ] ==> /tools/disk print-size
CMD [ /tools/install ] ==> truncate -s 9126805504 ./.cache/blikvm-pikvm-os.v3-hat.arch-rpi4-arm.img
CMD [ /tools/install ] ==> losetup -f
Traceback (most recent call last):
  File "/tools/install", line 109, in <module>
    main()
  File "/tools/install", line 105, in main
    _install_image(options.devfs_prefix, options.root, options.image, options.compress, sys.stdin.read())
  File "/tools/install", line 72, in _install_image
    _run(["mknod", loop_path, "b", "7", str(re.match(r".*(\d+)$", loop_path).group(1))])
                                            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'group'
make[1]: *** [Makefile:324: image] Error 1
make[1]: Leaving directory '/home/emory/blikvm_pikvm_build/.pi-builder/v3-hat-rpi4'
make: *** [Makefile:135: image] Error 2

```

**Comment by Kreeblah** [comment]
Unfortunately, there's probably not a whole lot I can do about that.  That's coming from https://github.com/pikvm/pi-builder/blob/master/toolbox/install#L72 which is looking for the results of `/root/$(losetup -f)` to set up a loopback device for writing the image to.  That should end with digits.  In my case, the next line in the output was:

```
CMD [ /tools/install ] ==> losetup /root//dev/loop0 ./.cache/blikvm-pikvm-os.v2-pcie.arch-rpi4-arm.img
```

As far as *why* it's not finding that, I'm not sure, and since it's that deeply embedded in pi-builder, there's probably not a ton I can do with what I'm doing with these makefiles.  The best I can suggest would be to maybe delete your Docker images that pi-builder downloaded/created, remove the cached data from the build process, and then start fresh.

**Comment by emorytaylor** [comment]
thanks it was the last thing I did before bed last night so I haven't tried anything yet, but I'll update you when it happens.

**Comment by emorytaylor** [comment]
It kept refusing to build on fedora, I ended up loading up a KVM and did it inside of ubuntu. Possibly my docker under fedora was too locked down. I will try installing it soon!

**Comment by emorytaylor** [comment]
I finally installed the image. h.264/webrtc isn't working which makes me think that something didn't install fully but I'm ok with it for the moment. if there's anything you'd want let me know, thanks!

**Comment by emorytaylor** [comment]
turns out h264 was working, just on a different browser, thanks again!

**Comment by Kreeblah** [comment]
Oh, nice!  Sounds like everything's working on your device, then?

**Comment by emorytaylor** [comment]
Yes, sorry for the delay but but it works. Thanks again.

**Comment by Kreeblah** [comment]
No worries.  I'm glad it ended up working!
